### ISSUE TITLE
Is it possible to override built-in block helpers?

### ISSUE THREAD

**Issue by hsamhita** [zjklee/Handlebars.CSharp#19]
I tried following to override "if" block helper, but didn't work.

            hnd.RegisterHelper("if", (output, options, context, args) =>
            {
                ...
                options.Template(output, context);
            });

**Comment by zjklee** [comment]
Short answer, **it's not possible**.

Long answer:
`if` does not implemented as a `BlockHelper`. Instead it is converted directly to `Expression.Condition(HandlebarsUtils.IsFalsyOrEmpty(argument) == false)` expression.

You can workaround this by transforming `if` parameter with `SubExpression`:
```csharp
[Fact]
public void If_Arg_Transformation()
{
    var source = "{{#if (Eq b a)}}equal{{else}}not equal{{/if}}";
    var handlebars = Handlebars.Create();
    handlebars.RegisterHelper("Eq", (context, arguments) => Equals(arguments[0], arguments[1]));
    
    var template = handlebars.Compile(source);
    
    var notEqualData = new { a = 42, b = 41 };
    var notEqual = template(notEqualData);
    Assert.Equal("not equal", notEqual);
    
    var equalData = new { a = 42, b = 42 };
    var equal = template(equalData);
    Assert.Equal("equal", equal);
}
```
