### ISSUE TITLE
Support lower .NET Framework version net451

### ISSUE THREAD

**Issue by StefH** [zjklee/Handlebars.CSharp#22]
Is it possible to support also support `net40` and `net451` for this library? I depend on version 451.

**HandleBars.Net**

> The https://www.nuget.org/packages/Handlebars.Net/1.9.0 did only have .NETFramework 4.0 as minimum requirement.
> 
> Since 1.9.3, this is moved to .NETFramework 4.5.2.

**Comment by zjklee** [comment]
I already have problems supporting `net452` (at least from language feature perspective) 😞
In any case I'd think on what can be done here 😉

**Comment by StefH** [comment]
I see.
( I did not know these two libraries yet... )

**Comment by zjklee** [comment]
@StefH 
I did some investigation and it seems that supporting net451 is possible (lower version would not fit in future plans).
I would update ‘ExpressionShortcuts‘ to support is as well. However if you need it in Handlebars I’d kindly ask you to create a PR as I have other things planned.
Acceptance criteria for the PR is to introduce thread-safe and fast ObjectPool implementation and use it as polyfill for net451.

**Comment by StefH** [comment]
- I can take a look at ExpressionShortcuts
- No need for polyfill, the ObjectPool version 1.1.1 already supports net451 : https://www.nuget.org/packages/Microsoft.Extensions.ObjectPool/1.1.1

**Comment by zjklee** [comment]
Yep, most probably I’ve missed it while was thinking more about net45 and lower 👍 

Then the only thing needed is to add net451 as supported framework to Handlebars as I’ve already fixed ‘ExpressionShortcuts’.

**Comment by StefH** [comment]
https://github.com/zjklee/Handlebars.CSharp/pull/24
