### ISSUE TITLE
RegisterHelper is obsolete, but what;s the replacement code?

### ISSUE THREAD

**Issue by StefH** [zjklee/Handlebars.CSharp#23]
``` cs
handlebars.RegisterHelper("ArrayTest", (writer, context, arguments) =>
            {
                var array = new object[]
                {
                    1,
                    "two"
                };

                writer.WriteSafeString($"[{string.Join(", ", array)}]");
            });
```

Note : I'm writing a helper library for Handlebars.Net and when I also use your version, it complains about obsolete.

(See https://github.com/StefH/Handlebars.Net.Helpers for details)

**Comment by zjklee** [comment]
Originally I planned to fully replace it by return version of the helper. However recently I’ve decided not to deprecate the API. That means that in next version of the package it wouldn’t be marked as obsolete anymore.
